run:
  timeout: 5m
linters:
  enable:
  - bodyclose
  - deadcode
  - depguard
  - dogsled
  - dupl
  - errcheck
  - goconst
  - gocritic
  - gocyclo
  - gofmt
  - goimports
  - golint
  - goprintffuncname
  - gochecknoglobals
  - gochecknoinits
  - gosec
  - gosimple
  - govet
  - ineffassign
  - interfacer
  - misspell
  - nakedret
  - rowserrcheck
  - scopelint
  - staticcheck
  - structcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - varcheck
  - whitespace