name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: test
      run: go test -race -timeout=60s -coverprofile=$GITHUB_WORKSPACE/profile.cov ./...
    - name: install golangci-lint
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.26.0
    - name: run linters
      run: $GITHUB_WORKSPACE/golangci-lint run ./... ;
